### ISSUE TITLE
issue with failed make in windows

### ISSUE THREAD

**Issue by velociwabbit** [JoshuaWise/lzz-gyp#5]
Per your request... thanks

Windows does not have make and i cannot get the installation past this hurdle.
 
node deps/install

==> cwd: d:\ddesktop\better-sqlite3-master\node_modules\lzz-gyp\lzz-source
==> make -f Makefile.release
'"make"' is not recognized as an internal or external command,
operable program or batch file.

**Comment by velociwabbit** [comment]
One of the suggestions for better-sqlite3 troubleshooting installation is to set LZZ_COMPAT=1 

When you do this the index.js of lzz-gyp will  not detect the correct windows settings here:

```
if (/^(1|true|yes|on)$/i.test(process.env.LZZ_COMPAT)) {
	switch (process.platform) {
		case 'darwin': lzz = './lzz-compiled/osx'; buildNewLzz = false; break;
		case 'win32': lzz = './lzz-compiled/windows.exe'; buildNewLzz = false; break;
		case 'linux': lzz = './lzz-compiled/linux'; buildNewLzz = false; break;
		case 'freebsd': lzz = './lzz-compiled/bsd'; buildNewLzz = false; break; // provided by https://github.com/Morfent
	}
}
```

 and try to build with a make statement here:
```

	var prerequisite = Promise.resolve();
	if (buildNewLzz) {
		prerequisite = exec('make', ['-f', 'Makefile.release'], path.dirname(lzz));
	}

```

I will try to  remove the LZZ_COMPAT=1 environment setting to see if that fixes it and will report back

**Comment by JoshuaWise** [comment]
Great, I'm glad the standard install method is working for you
